Assignment_2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from telnetlib import LOGOUT
from django.urls import include, path
from main.views import create_product_flutter, show_main
from main.views import show_main, create_product
from main.views import show_main, create_product, show_xml
from main.views import show_main, create_product, show_xml, show_json
from main.views import show_main, create_product, show_xml, show_json, show_xml_by_id, show_json_by_id
from main.views import register
from main.views import login_user
from main.views import logout_user
from main.views import edit_product
from main.views import delete_product
from main.views import get_product_json
from main.views import add_product_ajax
from main.views import del_product_ajax

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-product/<int:id>', edit_product, name='edit_product'),
    path('delete/<int:id>', delete_product, name='delete_product'), 
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-product-ajax/', add_product_ajax, name='add_product_ajax'),
    path('delete-product-ajax/<int:id>', del_product_ajax, name='del_product_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
    path('auth/', include('authentication.urls'))

]

main/models.py
from django.db import models
from django.contrib.auth.models import User


class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    date_added = models.DateField(auto_now_add=True)
    amount = models.IntegerField(default=0)
    price = models.IntegerField(default=0)
    description = models.TextField()
    type = models.CharField(max_length=255, null=True)
    rarity= models.CharField(max_length=255, null=True)
    is_discount = models.BooleanField(default=False)
# Create your models here.

main/forms.py
from django.forms import ModelForm
from main.models import Product

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "price", "description","amount","type","rarity"]

main/views.py
import json
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from main.forms import ProductForm
from main.models import Product
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect,HttpResponseNotFound
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import logout as auth_logout


@login_required(login_url='/login')

def show_main(request):

    products = Product.objects.filter(user=request.user)


    context = {
        'name': request.user.username,
        'general': 'This is a project that is under work, this will be an rpg-themed inventory management project',
        'lore': 'Foster is a merchant in the city of sorus, he is known to be the best trader in the city with never before seen items and weapons.However, currently he has problems with managing his inventory and needs your help',
        'categories': 'There are 4 item categories listed by Foster, Sword, Bow, Shields, and Throwables. Melee weapons will fall to the Sword category, bows and other long range weapon falls to the Bow category, armors and any other defense item falls to the Shield category, and throwable projectiles fall in the Throwables category. Any other types of item will be considered Miscellaneous. Recently added products will be marked with a red text below of the cards',
        'products': products,
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, 'main.html', context)

def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_product.html", context)

def show_xml(request):
    data = Product.objects.all()

def show_xml(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Product.objects.all()

def show_json(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def edit_product(request, id):
    # Get product by ID
    product = Product.objects.get(pk = id)

    # Set product as instance of form
    form = ProductForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        # Save the form and return to home page
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_product.html", context)

def delete_product(request, id):
    # Get data by ID
    product = Product.objects.get(pk=id)
    # Delete data
    product.delete()
    # Return to the main page
    return HttpResponseRedirect(reverse('main:show_main'))

def get_product_json(request):
    product_item = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', product_item))

@csrf_exempt
def add_product_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        price = request.POST.get("price")
        description = request.POST.get("description")
        amount = request.POST.get("amount")
        type = request.POST.get("type")
        rarity = request.POST.get("rarity")
        user = request.user

        new_product = Product(name=name, price=price, description=description, user=user, type=type, rarity=rarity, amount=amount)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def del_product_ajax(request, id):
    if request.method == 'POST':
        product = Product.objects.get(pk = id)
        product.delete()
        return HttpResponse(b"DELETED",status = 201)
    return HttpResponseNotFound()

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Product.objects.create(
            user = request.user,
            name = data["name"],
            amount = int(data["price"]),
            price = int(data["price"]),
            description = data["description"],
            type = data["type"],
            rarity = data["rarity"],
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

# Create your views here.

main/templates/create_product.html
{% extends 'base.html' %} 

{% block content %}
{%load static%}
<head>
    <link rel="stylesheet" type="text/css" media="screen" href="{%static 'css/style.css'%}">
</head>
<body id="bg" style="background-image: url('{%static 'main/bg.jpeg'%}');">
    
<h1>Add New Product</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Add Product"/>
            </td>
        </tr>
    </table>
</form>


{% endblock %}

main/templates/edit_product.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

{%load static%}
<head>
    <link rel="stylesheet" type="text/css" media="screen" href="{%static 'css/style.css'%}">
</head>
<body id="bg" style="background-image: url('{%static 'main/bg.jpeg'%}');">

<h1>Edit Product</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Edit Product"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}

{%load static%}
<head>
    <link rel="stylesheet" type="text/css" media="screen" href="{%static 'css/style.css'%}">
</head>
<body id="bg" style="background-image: url('{%static 'main/bg2.jpeg'%}');">
</body>

<div class = "login">
    {%load static%}
    <head>
        <link rel="stylesheet" type="text/css" media="screen" href="{%static 'css/styling.css'%}">
    </head>
    <body>
    <div class="container">
            <div><h1>Welcome To Sorus</h1><br>
                <h4>Tell us who you are and the secret passphrase</h4><br>
                <form method="POST" action="">
                {% csrf_token %}
                <table>
                    <tr>
                        <td style="text-align: right;">Username:</td> 
                        <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                    </tr>
                            
                    <tr>
                        <td style="text-align: right;">Password:</td>
                        <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                    </tr>

                    <tr>
                        <td></td>
                        <td>
                            <button class="btn btn login_btn" type="submit" value="Login">Login</button>
                        </td>
                    </tr>
                </table>
            </form><br>
            {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}     
            
        Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a>

            </div>
        </div>
            
        </div>
    </div>
    </div>
    </body>
</div>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block meta %}
  {% load static %}
  <title>Foster's bag</title>
  <link rel="stylesheet", href="{% static 'css/style.css' %}">
  <link rel="stylesheet", href="{% static 'css/colors.css' %}">

{% endblock meta %}
{% block content %}
    <div>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">Alvin Zhafif Afilla PBP KKI</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              {%load static%}
                <head>
                    <link rel="stylesheet" type="text/css" media="screen" href="{%static 'css/colors.css'%}">
                </head>
              </button>
              <a href="{% url 'main:logout' %}">
                {%load static%}
                <head>
                    <link rel="stylesheet" type="text/css" media="screen" href="{%static 'css/colors.css'%}">
                </head>
                <button type="button" class="btn btn-dark btn-outline-light">
                    Logout
                </button>
            </a>
            </div>
          </nav>
    </div>

<body id="bg" style="background-image: url('{%static 'main/bg.jpeg'%}');">


<h1>Foster's Bag</h1>

<h4>Current Merchant:</h4>
<p>{{name}}</p>

<h4>Project Description:</h4>
<p>{{ general }}</p>
<p>{{ lore }}</p>

<h4>Category Classification</h4>
<p>{{categories}}</p>

<h4>There are 4 item rarity, ranked based on these colors</h4>
<div id="text2">
  <p>Uncommon</p>
</div>
<div id="text3">
  <p>Rare</p>
</div>
<div id="text4">
  <p>Epic</p>
</div>
<div id="text5">
  <p>Legendary</p>
</div>


<table id="product_table"></table>
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
          <div class="modal-content">
              <div class="modal-header">
                  <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                  <form id="form" onsubmit="return false;">
                      {% csrf_token %}
                      <div class="mb-3">
                          <label for="name" class="col-form-label">Name:</label>
                          <input type="text" class="form-control" id="name" name="name"></input>
                      </div>
                      <div class="mb-3">
                          <label for="price" class="col-form-label">Price:</label>
                          <input type="number" class="form-control" id="price" name="price"></input>
                      </div>
                      <div class="mb-3">
                          <label for="description" class="col-form-label">Description:</label>
                          <textarea class="form-control" id="description" name="description"></textarea>
                      </div>
                      <div class="mb-3">
                          <label for="description" class="col-form-label">Amount:</label>
                          <textarea class="form-control" id="amount" name="amount"></textarea>
                      </div>
                      <div class="mb-3">
                        <label for="description" class="col-form-label">Type:</label>
                        <textarea class="form-control" id="type" name="type"></textarea>
                    </div>
                    <div class="mb-3">
                      <label for="description" class="col-form-label">Rarity:</label>
                      <textarea class="form-control" id="rarity" name="rarity"></textarea>
                  </div>
                  </form>
              </div>
              <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                  <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Product</button>
              </div>
          </div>
      </div>
    </div>

    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Product by AJAX</button>
   

<br />

<h5>Last login session: {{ last_login }}</h5>

<script>
  async function getProducts() {
      return fetch("{% url 'main:get_product_json' %}").then((res) => res.json())
  }
  async function refreshProducts() {
        document.getElementById("product_table").innerHTML = ""
        const products = await getProducts()
        let htmlString = ""
        products.forEach((item) => {
            htmlString += `\n<tr>
              <div class="card" style="width: 18rem;">
              `
              if (item.fields.type == "Sword") {
                htmlString += `<p class="card-text">${item.fields.type}</p>
                <img class="card-img-top" src="{% static 'main/sword.jpeg' %}" alt="Card image cap">
                `
              }
              else if (item.fields.type == "Bow") {
                htmlString += `<p class="card-text">${item.fields.type}</p>
                <img class="card-img-top" src="{% static 'main/bow.jpeg' %}" alt="Card image cap">
                `
              }
              else if (item.fields.type == "Throwable") {
                htmlString += `<p class="card-text">${item.fields.type}</p>
                <img class="card-img-top" src="{% static 'main/throwable.jpeg' %}" alt="Card image cap">
                `
              }
              else if (item.fields.type == "Shield") {
                htmlString += `<p class="card-text">${item.fields.type}</p>
                <img class="card-img-top" src="{% static 'main/shield.jpeg' %}" alt="Card image cap">
                `
              }
              else{
                htmlString += `<p class="card-text">Miscellaneous</p>
                <img class="card-img-top" src="{% static 'main/huh.jpeg' %}" alt="Card image cap">
                `
              }
              `
              <div class="card-body">
               `
               if(item.fields.rarity == "Uncommon"){
                htmlString += `<p class="card-text" id="text2">${item.fields.name}</p>
                `
               }
               else if(item.fields.rarity == "Rare"){
                htmlString += `<p class="card-text" id="text3">${item.fields.name}</p>
                `
               }
               else if(item.fields.rarity == "Epic"){
                htmlString += `<p class="card-text" id="text4">${item.fields.name}</p>
                `
               }
               else if(item.fields.rarity == "Legendary"){
                htmlString += `<p class="card-text" id="text5">${item.fields.name}</p>
                `
               }
               
              htmlString += `<p class="card-text">${item.fields.description}</p>
              `
              htmlString += `<p class="card-text">Price: ${item.fields.price}</p>
              `
              htmlString += `<p class="card-text">Amount left: ${item.fields.amount}</p> 
              `
              htmlString += `<p class="card-text">Date-added: ${item.fields.date_added}</p> 
              `
              htmlString += `<button onclick="delete_product(${item.pk})">Delete Product by AJAX</button>
              `
               htmlString += '</div>'
            htmlString += '</div>'
        htmlString += '</tr>' 
        })
        
        document.getElementById("product_table").innerHTML = htmlString
    }

    function addProduct() {
        fetch("{% url 'main:add_product_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshProducts)

        document.getElementById("form").reset()
        return false
    }
    function delete_product(id){
      fetch("/delete-product-ajax/" + id, {
        method: "POST",
    }).then(refreshProducts)
      return false
    }
    
    document.getElementById("button_add").onclick = addProduct
    refreshProducts()
</script>

{% endblock content %}

</body>

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}  

{%load static%}
<head>
    <link rel="stylesheet" type="text/css" media="screen" href="{%static 'css/style.css'%}">
</head>
<body id="bg" style="background-image: url('{%static 'main/bg3.jpeg'%}');">


{%load static%}
<head>
    <link rel="stylesheet" type="text/css" media="screen" href="{%static 'css/colors.css'%}">
</head>
<div class = "login" id="text">
    <h1>Become A Citizen</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}